ALTER TYPE "CustomerWalletLedgerType" ADD VALUE IF NOT EXISTS 'CUSTOMER_REFERRAL_EARNED';
ALTER TYPE "CustomerWalletLedgerType" ADD VALUE IF NOT EXISTS 'CUSTOMER_REFERRAL_TAX_WITHHELD';
ALTER TYPE "CustomerWalletLedgerType" ADD VALUE IF NOT EXISTS 'CUSTOMER_REFERRAL_USED_FOR_SERVICE';
ALTER TYPE "CustomerWalletLedgerType" ADD VALUE IF NOT EXISTS 'CUSTOMER_REFERRAL_CASHOUT';
ALTER TYPE "CustomerWalletLedgerType" ADD VALUE IF NOT EXISTS 'CUSTOMER_REFERRAL_REVERSED';

ALTER TYPE "ProviderWalletLedgerType" ADD VALUE IF NOT EXISTS 'PARTNER_REFERRAL_EARNED';
ALTER TYPE "ProviderWalletLedgerType" ADD VALUE IF NOT EXISTS 'PARTNER_REFERRAL_TAX_WITHHELD';
ALTER TYPE "ProviderWalletLedgerType" ADD VALUE IF NOT EXISTS 'OFFSET_PLATFORM_FEE';
ALTER TYPE "ProviderWalletLedgerType" ADD VALUE IF NOT EXISTS 'OFFSET_PARTNER_TAX';
ALTER TYPE "ProviderWalletLedgerType" ADD VALUE IF NOT EXISTS 'OFFSET_NEGATIVE_WALLET';
ALTER TYPE "ProviderWalletLedgerType" ADD VALUE IF NOT EXISTS 'PARTNER_REFERRAL_CASHOUT';
ALTER TYPE "ProviderWalletLedgerType" ADD VALUE IF NOT EXISTS 'PARTNER_REFERRAL_REVERSED';
