import 'package:flutter/material.dart';

String referralText(Locale locale, String key) {
  final language =
      _copy.containsKey(locale.languageCode) ? locale.languageCode : 'vi';
  return _copy[language]?[key] ?? _copy['vi']![key] ?? key;
}

String referralTextWith(
  Locale locale,
  String key,
  Map<String, Object?> values,
) {
  var text = referralText(locale, key);
  for (final entry in values.entries) {
    text = text.replaceAll('{${entry.key}}', '${entry.value ?? ''}');
  }
  return text;
}

const _copy = <String, Map<String, String>>{
  'vi': {
    'title': 'Giới thiệu bạn bè',
    'introTitle': 'Chia sẻ HANDS, nhận thêm phần thưởng',
    'introBody':
        'Mời bạn bè trải nghiệm HANDS. Khi họ hoàn tất điều kiện của chương trình, phần thưởng sẽ được ghi nhận theo chính sách hiện hành.',
    'step1Title': '1. Mời bạn bè',
    'step1Body': 'Gửi liên kết giới thiệu HANDS của bạn.',
    'step2Title': '2. Nhận phần thưởng',
    'step2Body': 'Phần thưởng được ghi nhận sau khi điều kiện hợp lệ hoàn tất.',
    'step3Title': '3. Sử dụng hoặc rút thưởng',
    'step3Body':
        'Dùng số dư cho dịch vụ HANDS hoặc yêu cầu rút khi phần thưởng đủ điều kiện.',
    'start': 'Bắt đầu nhận thưởng',
    'help': 'Hướng dẫn giới thiệu',
    'close': 'Đóng',
    'inactiveTitle': 'Chương trình hiện đang tạm dừng',
    'inactiveBody':
        'Bạn vẫn có thể xem lịch sử. Việc tạo mã và đăng ký giới thiệu mới đang bị tạm dừng.',
    'policyPercent': 'Nhận {value}% theo giá trị tính thưởng của chính sách.',
    'policyFixed': 'Nhận cố định {value} {currency} cho mỗi lần đủ điều kiện.',
    'policyHold': 'Phần thưởng được giữ {days} ngày trước khi có thể xử lý.',
    'policyMaxFriends': 'Tối đa {count} lượt giới thiệu được thưởng.',
    'policyMaxRewards':
        'Tối đa {count} phần thưởng cho mỗi người được giới thiệu.',
    'policyPerCap': 'Mỗi phần thưởng tối đa {value} {currency}.',
    'policyTotalCap': 'Tổng phần thưởng tối đa {value} {currency}.',
    'loadError': 'Không thể tải thông tin giới thiệu.',
    'retry': 'Thử lại',
    'codeReady': 'Mã giới thiệu của bạn đã sẵn sàng.',
    'codeIssueError': 'Không thể tạo mã giới thiệu.',
    'myCode': 'Liên kết giới thiệu của tôi',
    'copy': 'Sao chép liên kết',
    'copied': 'Đã sao chép liên kết giới thiệu.',
    'copyError': 'Không thể sao chép liên kết.',
    'details': 'Tổng quan giới thiệu',
    'friends': 'Bạn đã mời',
    'totalReward': 'Tổng phần thưởng',
    'processing': 'Chưa chi / đang xử lý',
    'paidOut': 'Đã rút',
    'invitedFriends': 'Bạn bè được giới thiệu',
    'rewardDetails': 'Chi tiết phần thưởng',
    'noInvites': 'Chưa có bạn bè nào tham gia qua liên kết của bạn.',
    'noRewards': 'Phần thưởng sẽ xuất hiện sau khi điều kiện hợp lệ hoàn tất.',
    'listError': 'Không thể tải danh sách này.',
    'loadMore': 'Xem thêm',
    'conditionMet': 'Đã đạt điều kiện thưởng',
    'conditionPending': 'Chưa đạt điều kiện thưởng',
    'attributedOn': 'Tham gia {date}',
    'booking': 'Đặt lịch {reference}',
    'availableOn': 'Có thể xử lý từ {date}',
    'cashout': 'Yêu cầu rút',
    'cashoutRequested': 'Yêu cầu rút đã được gửi.',
    'cashoutError': 'Không thể gửi yêu cầu rút.',
    'cashoutAlready': 'Phần thưởng này đang được xử lý hoặc đã hoàn tất.',
    'cashoutBalance': 'Số dư ví hiện tại không đủ để rút phần thưởng này.',
    'cashoutUnavailable': 'Phần thưởng này chưa đủ điều kiện rút.',
    'haveCode': 'Bạn có mã giới thiệu?',
    'claimHelp': 'Nhập mã của người đã giới thiệu bạn.',
    'codeLabel': 'Mã giới thiệu',
    'apply': 'Áp dụng mã',
    'enterCode': 'Vui lòng nhập mã giới thiệu.',
    'claimSuccess': 'Mã giới thiệu đã được áp dụng.',
    'claimError': 'Không thể áp dụng mã này. Hãy kiểm tra và thử lại.',
    'statusRegistered': 'Đã đăng ký',
    'statusQualified': 'Đủ điều kiện',
    'statusRewarded': 'Đã ghi nhận',
    'statusBlocked': 'Bị giữ để kiểm tra',
    'statusCancelled': 'Đã hủy',
    'rewardPending': 'Đang chờ',
    'rewardAvailable': 'Có thể ghi nhận',
    'rewardCredited': 'Đã cộng vào ví',
    'rewardUsed': 'Đã dùng cho dịch vụ',
    'rewardCashoutRequested': 'Đã yêu cầu rút',
    'rewardCashoutApproved': 'Đã duyệt rút',
    'rewardPaid': 'Đã thanh toán',
    'rewardHeld': 'Đang giữ',
    'rewardReversed': 'Đã thu hồi',
    'rewardCancelled': 'Đã hủy',
    'rewardReview': 'Đang kiểm tra',
  },
  'en': {
    'title': 'Referrals',
    'introTitle': 'Share HANDS and get rewarded',
    'introBody':
        'Invite friends to experience HANDS. Rewards follow the active policy after they complete an eligible activity.',
    'step1Title': '1. Invite a friend',
    'step1Body': 'Send your HANDS referral link.',
    'step2Title': '2. Earn rewards',
    'step2Body': 'Rewards are recorded after eligible activity is completed.',
    'step3Title': '3. Use or withdraw rewards',
    'step3Body':
        'Use wallet credit for HANDS services or request cashout when eligible.',
    'start': 'Start earning rewards',
    'help': 'Referral help',
    'close': 'Close',
    'inactiveTitle': 'The referral program is paused',
    'inactiveBody':
        'History remains available, but new codes and claims are disabled.',
    'policyPercent': 'Earn {value}% of the policy reward base.',
    'policyFixed': 'Earn {value} {currency} for each eligible reward.',
    'policyHold': 'Rewards are held for {days} day(s) before processing.',
    'policyMaxFriends': 'Up to {count} rewarded referrals.',
    'policyMaxRewards': 'Up to {count} reward(s) per referred friend.',
    'policyPerCap': 'Each reward is capped at {value} {currency}.',
    'policyTotalCap': 'Total rewards are capped at {value} {currency}.',
    'loadError': 'Referral details could not be loaded.',
    'retry': 'Retry',
    'codeReady': 'Your referral code is ready.',
    'codeIssueError': 'A referral code could not be issued.',
    'myCode': 'My referral link',
    'copy': 'Copy referral link',
    'copied': 'Referral link copied.',
    'copyError': 'The referral link could not be copied.',
    'details': 'Referral overview',
    'friends': 'Invited friends',
    'totalReward': 'Total rewards',
    'processing': 'Unpaid / processing',
    'paidOut': 'Paid out',
    'invitedFriends': 'Invited friends',
    'rewardDetails': 'Reward details',
    'noInvites': 'No friends have joined through your link yet.',
    'noRewards': 'Rewards appear after an eligible activity is completed.',
    'listError': 'This list could not be loaded.',
    'loadMore': 'Load more',
    'conditionMet': 'Reward condition met',
    'conditionPending': 'Reward condition pending',
    'attributedOn': 'Joined {date}',
    'booking': 'Booking {reference}',
    'availableOn': 'Available from {date}',
    'cashout': 'Request cashout',
    'cashoutRequested': 'Cashout request submitted.',
    'cashoutError': 'The cashout request could not be submitted.',
    'cashoutAlready': 'This reward is already processing or complete.',
    'cashoutBalance': 'Your wallet balance cannot cover this cashout.',
    'cashoutUnavailable': 'This reward is not eligible for cashout yet.',
    'haveCode': 'Have a referral code?',
    'claimHelp': 'Enter the code from the person who invited you.',
    'codeLabel': 'Referral code',
    'apply': 'Apply code',
    'enterCode': 'Enter a referral code.',
    'claimSuccess': 'Referral code applied.',
    'claimError': 'This code could not be applied. Check it and try again.',
    'statusRegistered': 'Registered',
    'statusQualified': 'Qualified',
    'statusRewarded': 'Rewarded',
    'statusBlocked': 'Held for review',
    'statusCancelled': 'Cancelled',
    'rewardPending': 'Pending',
    'rewardAvailable': 'Available',
    'rewardCredited': 'Added to wallet',
    'rewardUsed': 'Used for service',
    'rewardCashoutRequested': 'Cashout requested',
    'rewardCashoutApproved': 'Cashout approved',
    'rewardPaid': 'Paid',
    'rewardHeld': 'Held',
    'rewardReversed': 'Reversed',
    'rewardCancelled': 'Cancelled',
    'rewardReview': 'Under review',
  },
  'ko': {
    'title': '레퍼럴',
    'introTitle': 'HANDS를 나누고 보상을 받아보세요',
    'introBody': '친구를 HANDS로 초대하세요. 친구가 유효한 조건을 완료하면 현재 정책에 따라 보상이 적립됩니다.',
    'step1Title': '1. 친구 초대',
    'step1Body': '내 HANDS 추천 링크를 친구에게 보냅니다.',
    'step2Title': '2. 보상 적립',
    'step2Body': '친구가 유효한 조건을 완료하면 보상이 기록됩니다.',
    'step3Title': '3. 보상 사용 또는 출금',
    'step3Body': 'HANDS 서비스 결제에 사용하거나 출금 가능할 때 요청합니다.',
    'start': '리워드 시작하기',
    'help': '레퍼럴 도움말',
    'close': '닫기',
    'inactiveTitle': '레퍼럴 프로그램이 일시 중지되었습니다',
    'inactiveBody': '기존 내역은 볼 수 있지만 신규 코드 발급과 추천 등록은 중지됩니다.',
    'policyPercent': '정책의 보상 기준 금액 중 {value}%를 받습니다.',
    'policyFixed': '조건 달성마다 {value} {currency}를 받습니다.',
    'policyHold': '보상은 처리 전 {days}일 동안 보류됩니다.',
    'policyMaxFriends': '최대 {count}건의 추천에 보상됩니다.',
    'policyMaxRewards': '추천받은 친구 1명당 최대 {count}회 보상됩니다.',
    'policyPerCap': '1회 보상 상한은 {value} {currency}입니다.',
    'policyTotalCap': '총 보상 상한은 {value} {currency}입니다.',
    'loadError': '레퍼럴 정보를 불러오지 못했습니다.',
    'retry': '다시 시도',
    'codeReady': '추천 코드가 준비되었습니다.',
    'codeIssueError': '추천 코드를 발급하지 못했습니다.',
    'myCode': '내 추천 링크',
    'copy': '추천 링크 복사',
    'copied': '추천 링크를 복사했습니다.',
    'copyError': '추천 링크를 복사하지 못했습니다.',
    'details': '추천 현황',
    'friends': '초대한 친구',
    'totalReward': '총 보상',
    'processing': '미지급 / 처리 중',
    'paidOut': '출금 완료',
    'invitedFriends': '초대한 친구',
    'rewardDetails': '리워드 내역',
    'noInvites': '아직 추천 링크로 가입한 친구가 없습니다.',
    'noRewards': '친구가 유효한 조건을 완료하면 보상이 표시됩니다.',
    'listError': '목록을 불러오지 못했습니다.',
    'loadMore': '더 보기',
    'conditionMet': '보상 조건 달성',
    'conditionPending': '보상 조건 대기',
    'attributedOn': '{date} 가입',
    'booking': '예약 {reference}',
    'availableOn': '{date}부터 처리 가능',
    'cashout': '출금 요청',
    'cashoutRequested': '출금 요청을 접수했습니다.',
    'cashoutError': '출금 요청을 접수하지 못했습니다.',
    'cashoutAlready': '이미 처리 중이거나 완료된 보상입니다.',
    'cashoutBalance': '현재 월렛 잔액으로 이 보상을 출금할 수 없습니다.',
    'cashoutUnavailable': '아직 출금할 수 없는 보상입니다.',
    'haveCode': '추천 코드를 받으셨나요?',
    'claimHelp': '나를 초대한 사람의 코드를 입력합니다.',
    'codeLabel': '추천 코드',
    'apply': '코드 등록',
    'enterCode': '추천 코드를 입력해 주세요.',
    'claimSuccess': '추천 코드를 등록했습니다.',
    'claimError': '코드를 등록하지 못했습니다. 확인 후 다시 시도해 주세요.',
    'statusRegistered': '가입 완료',
    'statusQualified': '조건 달성',
    'statusRewarded': '보상 완료',
    'statusBlocked': '검토 보류',
    'statusCancelled': '취소',
    'rewardPending': '적립 대기',
    'rewardAvailable': '적립 가능',
    'rewardCredited': '월렛 적립',
    'rewardUsed': '서비스 결제 사용',
    'rewardCashoutRequested': '출금 요청',
    'rewardCashoutApproved': '출금 승인',
    'rewardPaid': '지급 완료',
    'rewardHeld': '보류',
    'rewardReversed': '회수',
    'rewardCancelled': '취소',
    'rewardReview': '검토 중',
  },
  'ja': {
    'title': '紹介',
    'introTitle': 'HANDSを紹介して特典を受け取りましょう',
    'introBody': '友だちが対象条件を完了すると、現在のポリシーに基づいて特典が記録されます。',
    'step1Title': '1. 友だちを招待',
    'step1Body': 'HANDSの紹介リンクを送ります。',
    'step2Title': '2. 特典を獲得',
    'step2Body': '対象条件の完了後に特典が記録されます。',
    'step3Title': '3. 特典を利用・出金',
    'step3Body': 'HANDSの支払いに使うか、対象になった特典を出金申請します。',
    'start': '特典を始める',
    'help': '紹介ヘルプ',
    'close': '閉じる',
    'inactiveTitle': '紹介プログラムは一時停止中です',
    'inactiveBody': '履歴は確認できますが、新規コード発行と登録は停止しています。',
    'policyPercent': 'ポリシーの報酬基準額の{value}%を受け取ります。',
    'policyFixed': '条件達成ごとに{value} {currency}を受け取ります。',
    'policyHold': '特典は処理前に{days}日間保留されます。',
    'policyMaxFriends': '特典対象の紹介は最大{count}件です。',
    'policyMaxRewards': '紹介された1人につき最大{count}回です。',
    'policyPerCap': '1回の上限は{value} {currency}です。',
    'policyTotalCap': '特典総額の上限は{value} {currency}です。',
    'loadError': '紹介情報を読み込めませんでした。',
    'retry': '再試行',
    'codeReady': '紹介コードを準備しました。',
    'codeIssueError': '紹介コードを発行できませんでした。',
    'myCode': '紹介リンク',
    'copy': 'リンクをコピー',
    'copied': '紹介リンクをコピーしました。',
    'copyError': '紹介リンクをコピーできませんでした。',
    'details': '紹介状況',
    'friends': '招待した友だち',
    'totalReward': '特典総額',
    'processing': '未払い・処理中',
    'paidOut': '出金完了',
    'invitedFriends': '招待した友だち',
    'rewardDetails': '特典履歴',
    'noInvites': '紹介リンクから参加した友だちはまだいません。',
    'noRewards': '対象条件の完了後に特典が表示されます。',
    'listError': '一覧を読み込めませんでした。',
    'loadMore': 'もっと見る',
    'conditionMet': '特典条件達成',
    'conditionPending': '特典条件待ち',
    'attributedOn': '{date}に参加',
    'booking': '予約 {reference}',
    'availableOn': '{date}から処理可能',
    'cashout': '出金申請',
    'cashoutRequested': '出金申請を送信しました。',
    'cashoutError': '出金申請を送信できませんでした。',
    'cashoutAlready': 'この特典は処理中または完了済みです。',
    'cashoutBalance': '現在のウォレット残高では出金できません。',
    'cashoutUnavailable': 'この特典はまだ出金できません。',
    'haveCode': '紹介コードをお持ちですか？',
    'claimHelp': '招待者から受け取ったコードを入力します。',
    'codeLabel': '紹介コード',
    'apply': 'コードを登録',
    'enterCode': '紹介コードを入力してください。',
    'claimSuccess': '紹介コードを登録しました。',
    'claimError': 'コードを登録できませんでした。確認して再試行してください。',
    'statusRegistered': '登録済み',
    'statusQualified': '条件達成',
    'statusRewarded': '特典完了',
    'statusBlocked': '確認保留',
    'statusCancelled': 'キャンセル',
    'rewardPending': '保留中',
    'rewardAvailable': '利用可能',
    'rewardCredited': 'ウォレット反映済み',
    'rewardUsed': 'サービスで使用済み',
    'rewardCashoutRequested': '出金申請済み',
    'rewardCashoutApproved': '出金承認済み',
    'rewardPaid': '支払済み',
    'rewardHeld': '保留',
    'rewardReversed': '回収済み',
    'rewardCancelled': 'キャンセル',
    'rewardReview': '確認中',
  },
  'zh': {
    'title': '推荐奖励',
    'introTitle': '分享 HANDS，获得奖励',
    'introBody': '邀请好友体验 HANDS。好友完成有效条件后，将按当前政策记录奖励。',
    'step1Title': '1. 邀请好友',
    'step1Body': '发送您的 HANDS 推荐链接。',
    'step2Title': '2. 获得奖励',
    'step2Body': '完成有效条件后记录奖励。',
    'step3Title': '3. 使用或提现',
    'step3Body': '可用于 HANDS 服务，符合条件时也可申请提现。',
    'start': '开始获得奖励',
    'help': '推荐帮助',
    'close': '关闭',
    'inactiveTitle': '推荐计划已暂停',
    'inactiveBody': '仍可查看历史记录，但无法新建代码或登记推荐。',
    'policyPercent': '获得政策奖励基数的 {value}%。',
    'policyFixed': '每次符合条件可获得 {value} {currency}。',
    'policyHold': '奖励处理前将保留 {days} 天。',
    'policyMaxFriends': '最多奖励 {count} 次推荐。',
    'policyMaxRewards': '每位被推荐好友最多奖励 {count} 次。',
    'policyPerCap': '单次奖励上限为 {value} {currency}。',
    'policyTotalCap': '总奖励上限为 {value} {currency}。',
    'loadError': '无法加载推荐信息。',
    'retry': '重试',
    'codeReady': '您的推荐代码已准备好。',
    'codeIssueError': '无法生成推荐代码。',
    'myCode': '我的推荐链接',
    'copy': '复制推荐链接',
    'copied': '已复制推荐链接。',
    'copyError': '无法复制推荐链接。',
    'details': '推荐概览',
    'friends': '已邀请好友',
    'totalReward': '奖励总额',
    'processing': '未支付 / 处理中',
    'paidOut': '已提现',
    'invitedFriends': '已邀请好友',
    'rewardDetails': '奖励明细',
    'noInvites': '还没有好友通过您的链接加入。',
    'noRewards': '好友完成有效条件后，奖励将显示在这里。',
    'listError': '无法加载此列表。',
    'loadMore': '查看更多',
    'conditionMet': '已达到奖励条件',
    'conditionPending': '等待奖励条件',
    'attributedOn': '{date} 加入',
    'booking': '预约 {reference}',
    'availableOn': '{date} 起可处理',
    'cashout': '申请提现',
    'cashoutRequested': '提现申请已提交。',
    'cashoutError': '无法提交提现申请。',
    'cashoutAlready': '该奖励正在处理或已完成。',
    'cashoutBalance': '当前钱包余额不足以提现该奖励。',
    'cashoutUnavailable': '该奖励暂不可提现。',
    'haveCode': '您有推荐代码吗？',
    'claimHelp': '输入邀请人提供的代码。',
    'codeLabel': '推荐代码',
    'apply': '使用代码',
    'enterCode': '请输入推荐代码。',
    'claimSuccess': '推荐代码已使用。',
    'claimError': '无法使用该代码，请检查后重试。',
    'statusRegistered': '已登记',
    'statusQualified': '已达标',
    'statusRewarded': '已奖励',
    'statusBlocked': '审核保留',
    'statusCancelled': '已取消',
    'rewardPending': '待处理',
    'rewardAvailable': '可用',
    'rewardCredited': '已存入钱包',
    'rewardUsed': '已用于服务',
    'rewardCashoutRequested': '已申请提现',
    'rewardCashoutApproved': '提现已批准',
    'rewardPaid': '已支付',
    'rewardHeld': '保留中',
    'rewardReversed': '已收回',
    'rewardCancelled': '已取消',
    'rewardReview': '审核中',
  },
};
