// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/admin-operators" | "/app-sessions" | "/audit-log" | "/background-jobs" | "/background-jobs/incidents/[id]" | "/bookings" | "/bookings/[id]" | "/bookings/completed" | "/bookings/post-match-cancellations" | "/calendar" | "/cash-settlements" | "/chat-archive" | "/coupons" | "/customers" | "/customers/[id]" | "/earnings" | "/files" | "/finance-closeout" | "/finance-overview" | "/finance-tax" | "/finance-tax/approval-queue" | "/finance-tax/bank-reconciliation" | "/finance-tax/bank-reconciliation/[id]" | "/finance-tax/bank-reconciliation/import-batches/[batchImportId]" | "/finance-tax/booking-settlement-audit" | "/finance-tax/booking-settlement-audit/[id]" | "/finance-tax/company-bank-accounts" | "/finance-tax/coupon-finance" | "/finance-tax/finance-approvers" | "/finance-tax/general-ledger" | "/finance-tax/general-ledger/[id]" | "/finance-tax/monthly-tax-closing" | "/finance-tax/partner-bank-deposits" | "/finance-tax/partner-bank-deposits/[id]" | "/finance-tax/partner-withholding-tax" | "/finance-tax/payment-clearing" | "/finance-tax/payment-clearing/[id]" | "/finance-tax/payment-fees" | "/finance-tax/platform-vat" | "/finance-tax/settlement-reversals" | "/finance-tax/settlement-reversals/[id]" | "/login" | "/marketing-analytics" | "/notifications" | "/notifications/push-send" | "/notifications/templates" | "/operations-handoff" | "/operations-policy" | "/partner-controls" | "/partners" | "/partners/[id]" | "/partners/overview" | "/payments" | "/payments/[id]" | "/payouts" | "/providers" | "/providers/[id]" | "/referrals" | "/referrals/cashouts" | "/referrals/customers" | "/referrals/customers/[id]" | "/referrals/partners" | "/referrals/partners/[id]" | "/refunds" | "/reviews" | "/reviews/partner-customer-evaluations" | "/services" | "/setup" | "/tax-policy" | "/usage-overview" | "/vietnam-overview" | "/wallet-adjustments" | "/website-content"
type AppRouteHandlerRoutes = "/api/admin/bank-reconciliation/batch-import" | "/api/admin/bank-reconciliation/batch-preview" | "/api/admin/bank-reconciliation/import-batches/[batchImportId]/export" | "/api/admin/bookings/[id]/chat-messages" | "/api/admin/calendar-events" | "/api/admin/calendar-events/[id]" | "/api/admin/customers/[id]/activity/export" | "/api/admin/customers/export" | "/api/admin/finance-tax/booking-settlement-audit/export" | "/api/admin/finance-tax/coupon-finance/export" | "/api/admin/finance-tax/monthly-tax-closing/export" | "/api/admin/finance-tax/partner-withholding-tax/export" | "/api/admin/finance-tax/payment-fees/export" | "/api/admin/finance-tax/platform-vat/export" | "/api/admin/geoapify-tiles/[z]/[x]/[y]" | "/api/admin/maptiler-tiles/[z]/[x]/[y]" | "/api/admin/partners/export" | "/api/admin/realtime-token" | "/api/admin/session/login" | "/api/admin/session/logout" | "/api/admin/session/me" | "/files/[id]/open" | "/r/[audience]/[code]" | "/reviews/export"
type PageRoutes = never
type LayoutRoutes = "/"
type RedirectRoutes = "/partner-risk" | "/provider-risk"
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/admin-operators": {}
  "/api/admin/bank-reconciliation/batch-import": {}
  "/api/admin/bank-reconciliation/batch-preview": {}
  "/api/admin/bank-reconciliation/import-batches/[batchImportId]/export": { "batchImportId": string; }
  "/api/admin/bookings/[id]/chat-messages": { "id": string; }
  "/api/admin/calendar-events": {}
  "/api/admin/calendar-events/[id]": { "id": string; }
  "/api/admin/customers/[id]/activity/export": { "id": string; }
  "/api/admin/customers/export": {}
  "/api/admin/finance-tax/booking-settlement-audit/export": {}
  "/api/admin/finance-tax/coupon-finance/export": {}
  "/api/admin/finance-tax/monthly-tax-closing/export": {}
  "/api/admin/finance-tax/partner-withholding-tax/export": {}
  "/api/admin/finance-tax/payment-fees/export": {}
  "/api/admin/finance-tax/platform-vat/export": {}
  "/api/admin/geoapify-tiles/[z]/[x]/[y]": { "z": string; "x": string; "y": string; }
  "/api/admin/maptiler-tiles/[z]/[x]/[y]": { "z": string; "x": string; "y": string; }
  "/api/admin/partners/export": {}
  "/api/admin/realtime-token": {}
  "/api/admin/session/login": {}
  "/api/admin/session/logout": {}
  "/api/admin/session/me": {}
  "/app-sessions": {}
  "/audit-log": {}
  "/background-jobs": {}
  "/background-jobs/incidents/[id]": { "id": string; }
  "/bookings": {}
  "/bookings/[id]": { "id": string; }
  "/bookings/completed": {}
  "/bookings/post-match-cancellations": {}
  "/calendar": {}
  "/cash-settlements": {}
  "/chat-archive": {}
  "/coupons": {}
  "/customers": {}
  "/customers/[id]": { "id": string; }
  "/earnings": {}
  "/files": {}
  "/files/[id]/open": { "id": string; }
  "/finance-closeout": {}
  "/finance-overview": {}
  "/finance-tax": {}
  "/finance-tax/approval-queue": {}
  "/finance-tax/bank-reconciliation": {}
  "/finance-tax/bank-reconciliation/[id]": { "id": string; }
  "/finance-tax/bank-reconciliation/import-batches/[batchImportId]": { "batchImportId": string; }
  "/finance-tax/booking-settlement-audit": {}
  "/finance-tax/booking-settlement-audit/[id]": { "id": string; }
  "/finance-tax/company-bank-accounts": {}
  "/finance-tax/coupon-finance": {}
  "/finance-tax/finance-approvers": {}
  "/finance-tax/general-ledger": {}
  "/finance-tax/general-ledger/[id]": { "id": string; }
  "/finance-tax/monthly-tax-closing": {}
  "/finance-tax/partner-bank-deposits": {}
  "/finance-tax/partner-bank-deposits/[id]": { "id": string; }
  "/finance-tax/partner-withholding-tax": {}
  "/finance-tax/payment-clearing": {}
  "/finance-tax/payment-clearing/[id]": { "id": string; }
  "/finance-tax/payment-fees": {}
  "/finance-tax/platform-vat": {}
  "/finance-tax/settlement-reversals": {}
  "/finance-tax/settlement-reversals/[id]": { "id": string; }
  "/login": {}
  "/marketing-analytics": {}
  "/notifications": {}
  "/notifications/push-send": {}
  "/notifications/templates": {}
  "/operations-handoff": {}
  "/operations-policy": {}
  "/partner-controls": {}
  "/partner-risk": {}
  "/partners": {}
  "/partners/[id]": { "id": string; }
  "/partners/overview": {}
  "/payments": {}
  "/payments/[id]": { "id": string; }
  "/payouts": {}
  "/provider-risk": {}
  "/providers": {}
  "/providers/[id]": { "id": string; }
  "/r/[audience]/[code]": { "audience": string; "code": string; }
  "/referrals": {}
  "/referrals/cashouts": {}
  "/referrals/customers": {}
  "/referrals/customers/[id]": { "id": string; }
  "/referrals/partners": {}
  "/referrals/partners/[id]": { "id": string; }
  "/refunds": {}
  "/reviews": {}
  "/reviews/export": {}
  "/reviews/partner-customer-evaluations": {}
  "/services": {}
  "/setup": {}
  "/tax-policy": {}
  "/usage-overview": {}
  "/vietnam-overview": {}
  "/wallet-adjustments": {}
  "/website-content": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
