// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../app/admin-operators/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin-operators">> = Specific
  const handler = {} as typeof import("../../app/admin-operators/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/app-sessions/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app-sessions">> = Specific
  const handler = {} as typeof import("../../app/app-sessions/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/audit-log/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/audit-log">> = Specific
  const handler = {} as typeof import("../../app/audit-log/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/background-jobs/incidents/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/background-jobs/incidents/[id]">> = Specific
  const handler = {} as typeof import("../../app/background-jobs/incidents/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/background-jobs/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/background-jobs">> = Specific
  const handler = {} as typeof import("../../app/background-jobs/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/bookings/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/bookings/[id]">> = Specific
  const handler = {} as typeof import("../../app/bookings/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/bookings/completed/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/bookings/completed">> = Specific
  const handler = {} as typeof import("../../app/bookings/completed/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/bookings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/bookings">> = Specific
  const handler = {} as typeof import("../../app/bookings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/bookings/post-match-cancellations/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/bookings/post-match-cancellations">> = Specific
  const handler = {} as typeof import("../../app/bookings/post-match-cancellations/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/calendar/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/calendar">> = Specific
  const handler = {} as typeof import("../../app/calendar/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/cash-settlements/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/cash-settlements">> = Specific
  const handler = {} as typeof import("../../app/cash-settlements/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/chat-archive/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/chat-archive">> = Specific
  const handler = {} as typeof import("../../app/chat-archive/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/coupons/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/coupons">> = Specific
  const handler = {} as typeof import("../../app/coupons/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/customers/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/customers/[id]">> = Specific
  const handler = {} as typeof import("../../app/customers/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/customers/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/customers">> = Specific
  const handler = {} as typeof import("../../app/customers/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/earnings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/earnings">> = Specific
  const handler = {} as typeof import("../../app/earnings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/files/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/files">> = Specific
  const handler = {} as typeof import("../../app/files/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/finance-closeout/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/finance-closeout">> = Specific
  const handler = {} as typeof import("../../app/finance-closeout/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/finance-overview/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/finance-overview">> = Specific
  const handler = {} as typeof import("../../app/finance-overview/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/finance-tax/approval-queue/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/finance-tax/approval-queue">> = Specific
  const handler = {} as typeof import("../../app/finance-tax/approval-queue/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/finance-tax/bank-reconciliation/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/finance-tax/bank-reconciliation/[id]">> = Specific
  const handler = {} as typeof import("../../app/finance-tax/bank-reconciliation/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/finance-tax/bank-reconciliation/import-batches/[batchImportId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/finance-tax/bank-reconciliation/import-batches/[batchImportId]">> = Specific
  const handler = {} as typeof import("../../app/finance-tax/bank-reconciliation/import-batches/[batchImportId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/finance-tax/bank-reconciliation/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/finance-tax/bank-reconciliation">> = Specific
  const handler = {} as typeof import("../../app/finance-tax/bank-reconciliation/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/finance-tax/booking-settlement-audit/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/finance-tax/booking-settlement-audit/[id]">> = Specific
  const handler = {} as typeof import("../../app/finance-tax/booking-settlement-audit/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/finance-tax/booking-settlement-audit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/finance-tax/booking-settlement-audit">> = Specific
  const handler = {} as typeof import("../../app/finance-tax/booking-settlement-audit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/finance-tax/company-bank-accounts/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/finance-tax/company-bank-accounts">> = Specific
  const handler = {} as typeof import("../../app/finance-tax/company-bank-accounts/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/finance-tax/coupon-finance/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/finance-tax/coupon-finance">> = Specific
  const handler = {} as typeof import("../../app/finance-tax/coupon-finance/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/finance-tax/finance-approvers/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/finance-tax/finance-approvers">> = Specific
  const handler = {} as typeof import("../../app/finance-tax/finance-approvers/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/finance-tax/general-ledger/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/finance-tax/general-ledger/[id]">> = Specific
  const handler = {} as typeof import("../../app/finance-tax/general-ledger/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/finance-tax/general-ledger/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/finance-tax/general-ledger">> = Specific
  const handler = {} as typeof import("../../app/finance-tax/general-ledger/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/finance-tax/monthly-tax-closing/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/finance-tax/monthly-tax-closing">> = Specific
  const handler = {} as typeof import("../../app/finance-tax/monthly-tax-closing/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/finance-tax/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/finance-tax">> = Specific
  const handler = {} as typeof import("../../app/finance-tax/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/finance-tax/partner-bank-deposits/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/finance-tax/partner-bank-deposits/[id]">> = Specific
  const handler = {} as typeof import("../../app/finance-tax/partner-bank-deposits/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/finance-tax/partner-bank-deposits/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/finance-tax/partner-bank-deposits">> = Specific
  const handler = {} as typeof import("../../app/finance-tax/partner-bank-deposits/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/finance-tax/partner-withholding-tax/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/finance-tax/partner-withholding-tax">> = Specific
  const handler = {} as typeof import("../../app/finance-tax/partner-withholding-tax/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/finance-tax/payment-clearing/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/finance-tax/payment-clearing/[id]">> = Specific
  const handler = {} as typeof import("../../app/finance-tax/payment-clearing/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/finance-tax/payment-clearing/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/finance-tax/payment-clearing">> = Specific
  const handler = {} as typeof import("../../app/finance-tax/payment-clearing/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/finance-tax/payment-fees/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/finance-tax/payment-fees">> = Specific
  const handler = {} as typeof import("../../app/finance-tax/payment-fees/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/finance-tax/platform-vat/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/finance-tax/platform-vat">> = Specific
  const handler = {} as typeof import("../../app/finance-tax/platform-vat/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/finance-tax/settlement-reversals/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/finance-tax/settlement-reversals/[id]">> = Specific
  const handler = {} as typeof import("../../app/finance-tax/settlement-reversals/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/finance-tax/settlement-reversals/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/finance-tax/settlement-reversals">> = Specific
  const handler = {} as typeof import("../../app/finance-tax/settlement-reversals/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../app/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/marketing-analytics/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/marketing-analytics">> = Specific
  const handler = {} as typeof import("../../app/marketing-analytics/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/notifications/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/notifications">> = Specific
  const handler = {} as typeof import("../../app/notifications/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/notifications/push-send/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/notifications/push-send">> = Specific
  const handler = {} as typeof import("../../app/notifications/push-send/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/notifications/templates/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/notifications/templates">> = Specific
  const handler = {} as typeof import("../../app/notifications/templates/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/operations-handoff/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/operations-handoff">> = Specific
  const handler = {} as typeof import("../../app/operations-handoff/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/operations-policy/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/operations-policy">> = Specific
  const handler = {} as typeof import("../../app/operations-policy/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/partner-controls/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/partner-controls">> = Specific
  const handler = {} as typeof import("../../app/partner-controls/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/partners/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/partners/[id]">> = Specific
  const handler = {} as typeof import("../../app/partners/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/partners/overview/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/partners/overview">> = Specific
  const handler = {} as typeof import("../../app/partners/overview/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/partners/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/partners">> = Specific
  const handler = {} as typeof import("../../app/partners/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/payments/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/payments/[id]">> = Specific
  const handler = {} as typeof import("../../app/payments/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/payments/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/payments">> = Specific
  const handler = {} as typeof import("../../app/payments/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/payouts/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/payouts">> = Specific
  const handler = {} as typeof import("../../app/payouts/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/providers/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/providers/[id]">> = Specific
  const handler = {} as typeof import("../../app/providers/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/providers/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/providers">> = Specific
  const handler = {} as typeof import("../../app/providers/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/referrals/cashouts/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/referrals/cashouts">> = Specific
  const handler = {} as typeof import("../../app/referrals/cashouts/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/referrals/customers/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/referrals/customers/[id]">> = Specific
  const handler = {} as typeof import("../../app/referrals/customers/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/referrals/customers/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/referrals/customers">> = Specific
  const handler = {} as typeof import("../../app/referrals/customers/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/referrals/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/referrals">> = Specific
  const handler = {} as typeof import("../../app/referrals/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/referrals/partners/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/referrals/partners/[id]">> = Specific
  const handler = {} as typeof import("../../app/referrals/partners/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/referrals/partners/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/referrals/partners">> = Specific
  const handler = {} as typeof import("../../app/referrals/partners/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/refunds/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/refunds">> = Specific
  const handler = {} as typeof import("../../app/refunds/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/reviews/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reviews">> = Specific
  const handler = {} as typeof import("../../app/reviews/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/reviews/partner-customer-evaluations/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reviews/partner-customer-evaluations">> = Specific
  const handler = {} as typeof import("../../app/reviews/partner-customer-evaluations/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/services/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/services">> = Specific
  const handler = {} as typeof import("../../app/services/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/setup/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/setup">> = Specific
  const handler = {} as typeof import("../../app/setup/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/tax-policy/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/tax-policy">> = Specific
  const handler = {} as typeof import("../../app/tax-policy/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/usage-overview/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/usage-overview">> = Specific
  const handler = {} as typeof import("../../app/usage-overview/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/vietnam-overview/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/vietnam-overview">> = Specific
  const handler = {} as typeof import("../../app/vietnam-overview/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/wallet-adjustments/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/wallet-adjustments">> = Specific
  const handler = {} as typeof import("../../app/wallet-adjustments/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/website-content/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/website-content">> = Specific
  const handler = {} as typeof import("../../app/website-content/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/bank-reconciliation/batch-import/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/bank-reconciliation/batch-import">> = Specific
  const handler = {} as typeof import("../../app/api/admin/bank-reconciliation/batch-import/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/bank-reconciliation/batch-preview/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/bank-reconciliation/batch-preview">> = Specific
  const handler = {} as typeof import("../../app/api/admin/bank-reconciliation/batch-preview/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/bank-reconciliation/import-batches/[batchImportId]/export/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/bank-reconciliation/import-batches/[batchImportId]/export">> = Specific
  const handler = {} as typeof import("../../app/api/admin/bank-reconciliation/import-batches/[batchImportId]/export/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/bookings/[id]/chat-messages/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/bookings/[id]/chat-messages">> = Specific
  const handler = {} as typeof import("../../app/api/admin/bookings/[id]/chat-messages/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/calendar-events/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/calendar-events/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/admin/calendar-events/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/calendar-events/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/calendar-events">> = Specific
  const handler = {} as typeof import("../../app/api/admin/calendar-events/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/customers/[id]/activity/export/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/customers/[id]/activity/export">> = Specific
  const handler = {} as typeof import("../../app/api/admin/customers/[id]/activity/export/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/customers/export/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/customers/export">> = Specific
  const handler = {} as typeof import("../../app/api/admin/customers/export/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/finance-tax/booking-settlement-audit/export/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/finance-tax/booking-settlement-audit/export">> = Specific
  const handler = {} as typeof import("../../app/api/admin/finance-tax/booking-settlement-audit/export/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/finance-tax/coupon-finance/export/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/finance-tax/coupon-finance/export">> = Specific
  const handler = {} as typeof import("../../app/api/admin/finance-tax/coupon-finance/export/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/finance-tax/monthly-tax-closing/export/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/finance-tax/monthly-tax-closing/export">> = Specific
  const handler = {} as typeof import("../../app/api/admin/finance-tax/monthly-tax-closing/export/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/finance-tax/partner-withholding-tax/export/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/finance-tax/partner-withholding-tax/export">> = Specific
  const handler = {} as typeof import("../../app/api/admin/finance-tax/partner-withholding-tax/export/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/finance-tax/payment-fees/export/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/finance-tax/payment-fees/export">> = Specific
  const handler = {} as typeof import("../../app/api/admin/finance-tax/payment-fees/export/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/finance-tax/platform-vat/export/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/finance-tax/platform-vat/export">> = Specific
  const handler = {} as typeof import("../../app/api/admin/finance-tax/platform-vat/export/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/geoapify-tiles/[z]/[x]/[y]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/geoapify-tiles/[z]/[x]/[y]">> = Specific
  const handler = {} as typeof import("../../app/api/admin/geoapify-tiles/[z]/[x]/[y]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/maptiler-tiles/[z]/[x]/[y]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/maptiler-tiles/[z]/[x]/[y]">> = Specific
  const handler = {} as typeof import("../../app/api/admin/maptiler-tiles/[z]/[x]/[y]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/partners/export/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/partners/export">> = Specific
  const handler = {} as typeof import("../../app/api/admin/partners/export/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/realtime-token/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/realtime-token">> = Specific
  const handler = {} as typeof import("../../app/api/admin/realtime-token/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/session/login/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/session/login">> = Specific
  const handler = {} as typeof import("../../app/api/admin/session/login/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/session/logout/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/session/logout">> = Specific
  const handler = {} as typeof import("../../app/api/admin/session/logout/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/session/me/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/session/me">> = Specific
  const handler = {} as typeof import("../../app/api/admin/session/me/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/files/[id]/open/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/files/[id]/open">> = Specific
  const handler = {} as typeof import("../../app/files/[id]/open/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/r/[audience]/[code]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/r/[audience]/[code]">> = Specific
  const handler = {} as typeof import("../../app/r/[audience]/[code]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/reviews/export/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/reviews/export">> = Specific
  const handler = {} as typeof import("../../app/reviews/export/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
