ALTER TYPE "AdminOperatorPermissionCategory" ADD VALUE IF NOT EXISTS 'GROWTH';
ALTER TYPE "AdminOperatorPermissionCategory" ADD VALUE IF NOT EXISTS 'GROWTH_MARKETING';
ALTER TYPE "AdminOperatorPermissionCategory" ADD VALUE IF NOT EXISTS 'DEVELOPER_SYSTEM';
ALTER TYPE "AdminOperatorPermissionCategory" ADD VALUE IF NOT EXISTS 'DEVELOPER_SETUP';
ALTER TYPE "AdminOperatorPermissionCategory" ADD VALUE IF NOT EXISTS 'DEVELOPER_HEALTH';
ALTER TYPE "AdminOperatorPermissionCategory" ADD VALUE IF NOT EXISTS 'DEVELOPER_APP_SESSIONS_DIAGNOSTICS';
ALTER TYPE "AdminOperatorPermissionCategory" ADD VALUE IF NOT EXISTS 'DEVELOPER_ROUTE_COMPAT';
