var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/_global-error/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__1dky4g0._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_19--w_z.js")
R.c("server/chunks/ssr/[root-of-the-server]__1qicfxx._.js")
R.c("server/chunks/ssr/node_modules_next_dist_0bz2d8m._.js")
R.c("server/chunks/ssr/node_modules_1wdusod._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0-o-goa.js")
R.c("server/chunks/ssr/apps_admin_web__next-internal_server_app__global-error_page_actions_1bgezga.js")
R.m(942378)
module.exports=R.m(942378).exports
